name: gitflow check

on:
  pull_request:
    branches: [main]

jobs:
  gitflow:
    runs-on: ubuntu-20.04
    steps:
    - name: Set environment variables
      run: |
        echo "GIT_BRANCH=${GITHUB_REF_NAME}" >> $GITHUB_ENV
    - name: Branch Name Check
      run: |
        ALLOWED="((feature|fix)\/[A-Z0-9a-z-]+)$"
        echo "branch is $GIT_BRANCH"
        if ! [[ "$GIT_BRANCH" =~ $ALLOWED ]]
        then
            echo "Wrong branch name"
            exit 1
        fi
        echo "Successful branch name check"