name: Test, Build And Deploy

on:
  pull_request:
    branches: [main]

jobs:
  test_build_deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Coverage Report
      env:
        TEST_COVERAGE_THRESHOLD: 80
      run: |
        ./test_coverage.sh
        TOTAL=$(go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+')
        if (( $(echo "$TOTAL <= $TEST_COVERAGE_THRESHOLD" | bc -l) ))
        then
            echo "Current test coverage is below threshold. ${TOTAL}% < ${TEST_COVERAGE_THRESHOLD}%"
            exit 1
        fi
        echo "Successful coverage test"